- name: Set up sudoers files for move trigger users
  copy: src=sudoers/{{item}} dest=/etc/sudoers.d/{{item}} mode=0440 backup=yes
  with_items:
    - linaro-android-build-publish-trigger
    - linaro-ci-publish-trigger
  sudo: yes

- name: Set top-level upload dir permissions
  file: dest=/home/linaro-android-build-publish/uploads/ state=directory
        owner=linaro-android-build-publish group=bot-publishers
        mode=0775
        #recurse=yes
  sudo: yes

- name: Set Android upload dir permissions
  file: dest=/home/linaro-android-build-publish/uploads/android/ state=directory
        owner=linaro-android-build-publish group=bot-publishers
        mode=0775
        #recurse=yes
  sudo: yes

# file recurse=yes is *very* slow in Ansible ;-(
#- name: Set download dir permissions
#  file: dest={{www_dir}} state=directory
#        owner=linaro-ci-publish group=bot-publishers
#        recurse=yes
#        #mode=0775
#  sudo: yes

- name: Set download dir permissions
  command: chown -R linaro-ci-publish:bot-publishers {{www_dir}}
  sudo: yes
