---
# Disable defaults and enable necessary modules.

- name: apache-conf-enable-modules
  command: a2enmod {{ item }}
           creates=/etc/apache2/mods-enabled/{{ item }}.load
  with_items:
      - ssl
      - wsgi
      - xsendfile
  notify: restart-apache
  tags:
    - install
    - apache-conf

- name: apache-conf-disable-default
  command:  a2dissite default
            removes=/etc/apache2/sites-enabled/000-default
  notify: restart-apache
  tags:
    - install
    - apache-conf
