---
# Set a sane visible nickname for the host. Since with Amazon it is not always
# possible to change the hostname if we do not have a registered DNS name
# associated with it, the other way to set it, as reported also by Amazon docs,
# is to set a NICKNAME variable, and tweak the PS1 variable to show that
# instead.
# This will only work for new users, already existing users will have to tweak
# their bashrc file accordingly.
#
# This role requires the variable 'hostname' to be set.
#

- name: host-nickname-var-file
  template: src=host-nickname.sh
            dest=/etc/profile.d/host-nickname.sh
            owner=root
            group=root
            mode=0444

# Install a default bashrc for new users.
- name: host-nickname-bashrc-addition
  template: src=base-bashrc
            dest=/etc/skel/.bashrc
            owner=root
            group=root
            mode=0644
