# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('license_protected_downloads', '0003_auto_20161216_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='digest',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
